
output   = "pkg/models"
wipe     = true
no-tests = true
debug    = false

[psql]
  dbname    = "perspex"
  host      = "127.0.0.1"
  port      = "5433"
  user      = "postgres"
  sslmode   = "disable"
  pass      = "pass"
  schema    = "public"
  blacklist = [
    "schema_migrations"
  ]

