{{- if .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend.name" . }}
  labels: 
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- with .Values.traefik.entrypoints }}
  entryPoints:
    {{- toYaml .| nindent 4 }}
  {{- end }}
  routes:
    - match: Host(`{{ .Values.traefik.host }}`) && PathPrefix(`{{ .Values.traefik.path }}`)
      kind: Rule
      {{- with .Values.traefik.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      services:
        - name: {{ include "backend.name" . }}
          kind: {{ if .Values.canary.enabled -}}TraefikService{{- else -}}Service{{- end}}
          port: {{ .Values.service.port }}
    {{- with .Values.traefik.additionalRoutes }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
