{{- if .Values.migration.enabled }}
{{ $fullname := include "perspex.fullname" . }}
{{- $jobName := include "perspex.uniqueName" (dict "root" . "job" "migration" "unique" true ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    {{- include "perspex.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": {{ .Values.migration.forward.hook.types }}
    "helm.sh/hook-delete-policy": {{ .Values.migration.forward.hook.deletePolicy }}
    "helm.sh/hook-weight": {{ .Values.migration.forward.hook.weight | quote }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ $jobName }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.postgresql.enabled }}
        - name: check-db-ready
          image: postgres:alpine
          command: [ 'sh', '-c', 'until pg_isready -U postgres -h postgresql.{{ $fullname }} -p 5432; do echo waiting for database; sleep 2; done;' ]
      {{- end }}
      containers:
        - name: {{ $jobName }}
          env:
            {{- include "perspex.environmentVariables" . | nindent 12 }}
            {{- range $key, $value := .Values.migration.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.migration.secretsManager.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.migration.secretsManager.secretName }}
          {{- end }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          {{- if .Values.migration.forward.enabled }} 
          command: {{ .Values.migration.forward.command | toJson }}
          extraArgs: {{ .Values.migration.forward.extraArgs | toJson }}
          {{- end }}
          {{- if .Values.migration.rollback.enabled }} 
          command: {{ .Values.migration.rollback.command | toJson }}
          extraArgs: {{ .Values.migration.rollback.extraArgs | toJson }}
          {{- end }}
          volumeMounts:
            - name: scripts
              mountPath: /usr/src/app/scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ $fullname }}-scripts
            defaultMode: 0777
{{- end }}
