name: backend-codegen-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
jobs:
  backend-codegen-linter:
    name: Backend Codegen Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update checkout
        run: git fetch --prune
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: '4.14.2'
          yq-url: 'https://github.com/mikefarah/yq/releases/download/v4.14.2/yq_linux_amd64'

      - name: Set environment variables
        id: set-environment-variables
        run: |
          echo "TILT_BACKEND_ENABLED=false" >> $GITHUB_ENV
          echo "TILT_REMOTE_CLUSTER=True" >> $GITHUB_ENV

      - name: Run helm dependency update
        run: |
          helm dependency update infrastructure/charts/perspex

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Install tilt
        run: |
          curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v0.23.1/tilt.0.23.1.linux.x86_64.tar.gz | tar -xzv tilt && \
          mv tilt /usr/local/bin/tilt

      - uses: AbsaOSS/k3d-action@v2
        name: "Spin up k3d"
        with:
          cluster-name: "perspex-ci"
          args: >-
            -c infrastructure/tilt/k3d-config.yaml

      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: '4.14.2'
          yq-url: 'https://github.com/mikefarah/yq/releases/download/v4.14.2/yq_linux_amd64'

      - name: Do some yaml substitutions
        run: |
          yq eval -i '.backend.enabled = "${TILT_BACKEND_ENABLED}"' infrastructure/tilt/values-dev.yaml

      - name: Update image repo in helm values
        run: |
          sed -i "s/registry.local:5000/450613976047.dkr.ecr.us-east-1.amazonaws.com\/development/g" infrastructure/tilt/values-dev.yaml

      - name: Run tilt up
        run: |
          echo $GITHUB_ENV
          printenv
          tilt ci -f Tiltfile
