name: backend-codegen-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
jobs:
  backend-codegen-linter:
    name: migration-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update checkout
        run: git fetch --prune
        shell: bash

      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: '4.14.2'
          yq-url: 'https://github.com/mikefarah/yq/releases/download/v4.14.2/yq_linux_amd64'

      - name: Set environment variables
        id: set-environment-variables
        run: |
          echo "TILT_BACKEND_ENABLED="false" >> $GITHUB_ENV
          echo "TILT_REMOTE_CLUSTER=True >> $GITHUB_ENV

      - name: Run helm dependency update
        run: |
          helm dependency update infrastructure/charts/perspex

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Install tilt
        run: |
          curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v0.23.1/tilt.0.23.1.linux.x86_64.tar.gz | tar -xzv tilt && \
          mv tilt /usr/local/bin/tilt

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Spin up k3d
        run: |
          k3d cluster create -c infrastructure/tilt/k3d-config.yaml

      - name: Run tilt up
        run: |
          tilt ci -f Tiltfile
