
name: migration-linter
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
jobs:
  migration-linter:
    name: Migration Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update checkout
        run: git fetch --prune
        shell: bash
      - id: modified-migrations
        name: Find modified migrations
        run: |
          modified_migrations=$(git diff --name-only origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} 'services/migration/src/**/*.sql')
          echo "$modified_migrations"

          echo "{file_names}={"${modified_migrations}"}" >> $GITHUB_OUTPUT

          for i in "${modified_migrations[@]}"; do
            # or do whatever with individual element of the array
            echo "origin/${GITHUB_BASE_REF}:${i}"
            does_file_exist=$(git cat-file -e "origin/${GITHUB_BASE_REF}:${i}")

            echo "${does_file_exist}"
            if [[ -v "${does_file_exist}" ]]; then
              echo "Error: this pr touches ${i}, which is a file already in history"
              exit 1;
            fi

          done
      - uses: sbdchd/squawk-action@v1
        with:
          pattern: ${{ steps.modified-migrations.outputs.file_names }}
