name: release-images
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
    paths:
      - ".github/workflows/release-images.yml"
      - "schemas/openapi/**/*"
      - "schemas/proto/**/*"
      - "services/migration/**/*.sql"
      - "services/**/*"

jobs:
  codegen-linter:
    name: Codegen Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update checkout
        run: git fetch --prune
        shell: bash

      - name: Set cluster environment variables
        id: set-environment-variables
        run: |
          echo "TILT_REMOTE_CLUSTER=false" >> ${GITHUB_ENV}
          echo "TILT_BACKEND_IMAGE_TARGET=deployable" >> ${GITHUB_ENV}

      - name: Disable all services
        id: disable-all-services
        run: |
          bin/release.sh -ds

      - name: Enable Changed services
        id: enable-changed-services
        run: |
          bin/release.sh -s

      - name: Run helm dependency update
        run: |
          bin/helm dependency update infrastructure/charts/perspex

      - name: Spin up k3d cluster
        run: |
          bin/k3d cluster create -c infrastructure/tilt/k3d-config.yaml

      - name: Run tilt up
        run: |
          bin/tilt ci -f Tiltfile

      - name: Verify Codegen is committed
        run: |
          bin/codegen-linter.sh -l
